DROP DATABASE IF EXISTS pokedon;

CREATE DATABASE pokedon;

USE pokedon;

CREATE TABLE pokemons (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  no INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  typing VARCHAR(100) NOT NULL
) AUTO_INCREMENT=1;